apiVersion: v1
kind: Service
metadata:
  name: s-data-acess-service
  namespace: development
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: data-access-service
  ports:
  - port: 80
    targetPort: 80